### ISSUE TITLE
Bater o ponto apenas com um command

### ISSUE THREAD

**Issue by jpdev01** [fmilani/ppp#12]
Opa, tem como bater o ponto usando apenas um command line?

Passando params, algo assim.

**Comment by fmilani** [comment]
Pra bater o ponto é só rodar `ppp ponto`.  O comando não aceita parametros, talvez eu não tenha entendido sua pergunta 😬

**Comment by jpdev01** [comment]
Opa, na verdade a ideia seria fazer um ppp login, ppp local, ppp ponto tudo só com um comando. Podendo criar um super alias para batidas de ponto.

**Comment by fmilani** [comment]
Mas o `login` e o `local` vc soh precisa rodar uma vez! Depois que rodou eles o `ponto` pode ser executado separado, por isso não faz sentido juntar tudo num comando só, saca?

**Comment by jpdev01** [comment]
@fmilani pensei que tinha que rodar sempre! Bom demais!
